package contracts

import (
	"bytes"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"reflect"
	"sort"
	"strings"

	"github.com/slycrel/maro-orchestration/go/internal/record"
)

const generatorID = "maro-go contracts gen v1"

// GenerateAll derives one Generated per registered kind. Pure: no I/O.
func GenerateAll(sourceRef string) []Generated {
	specs := record.All()
	out := make([]Generated, 0, len(specs))
	for _, s := range specs {
		out = append(out, generate(s, sourceRef))
	}
	return out
}

func generate(s record.Spec, sourceRef string) Generated {
	g := Generated{
		FormatVersion: FormatVersion,
		Kind:          string(s.Kind), Envelope: s.Envelope.String(),
		Schema: fmt.Sprintf("%s/%d", s.Kind, s.Version), GoType: s.Type.String(),
		SourceRef: sourceRef, Generator: generatorID,
	}
	g.Fields = fieldsOf(s.Type, "", false)
	return g
}

var (
	headerType = reflect.TypeOf(record.Header{})
	markerTys  = map[reflect.Type]bool{
		reflect.TypeOf(record.ProductionRecord{}): true, reflect.TypeOf(record.ControlRecord{}): true, reflect.TypeOf(record.ExperimentalRecord{}): true,
	}
)

func fieldsOf(t reflect.Type, prefix string, fromHeader bool) []GeneratedField {
	var out []GeneratedField
	for i := 0; i < t.NumField(); i++ {
		f := t.Field(i)
		if markerTys[f.Type] {
			continue
		}
		tag := f.Tag.Get("json")
		name, opts, _ := strings.Cut(tag, ",")
		if name == "-" {
			continue
		}
		if name == "" {
			name = f.Name
		}
		if f.Anonymous && f.Type == headerType {
			sub := fieldsOf(headerType, prefix+name+".", true)
			for i := range sub {
				sub[i].Embedded = true
			}
			out = append(out, sub...)
			continue
		}
		omit := strings.Contains(opts, "omitempty") || f.Type.Kind() == reflect.Pointer || f.Type.Kind() == reflect.Slice || f.Type.Kind() == reflect.Map
		isThought := strings.HasSuffix(f.Type.String(), "thought.Ref") || (f.Name == "Hash" && strings.Contains(t.String(), "Thought"))
		out = append(out, GeneratedField{
			Name: prefix + f.Name, Wire: prefix + name, GoType: f.Type.String(),
			Omittable: omit, IsThought: isThought, FromHeader: fromHeader,
		})
	}
	return out
}

// SourceRef returns the current git HEAD or "unknown".
func SourceRef() string {
	cmd := exec.Command("git", "rev-parse", "--short", "HEAD")
	out, err := cmd.Output()
	if err != nil {
		return "unknown"
	}
	return strings.TrimSpace(string(out))
}

// Manifest lists the generated files and their canonical hashes; written
// LAST by gen, so a crash mid-generation leaves a manifest that does not
// match and `check` fails instead of reading a mixed generation.
type Manifest struct {
	Generator string            `json:"generator"`
	SourceRef string            `json:"source_ref"`
	Kinds     map[string]string `json:"kinds"` // kind → sha256 of the canonical generated bytes with source_ref blanked
}

const manifestFile = "MANIFEST.json"

// WriteGenerated writes every generated file into dir, then the manifest.
func WriteGenerated(dir Dir, gens []Generated) error {
	if err := os.MkdirAll(string(dir), 0o755); err != nil {
		return err
	}
	m := Manifest{Generator: generatorID, Kinds: map[string]string{}}
	for _, g := range gens {
		if err := writeJSON(dir.genPath(g.Kind), g); err != nil {
			return err
		}
		m.Kinds[g.Kind] = digest(g)
		m.SourceRef = g.SourceRef
	}
	return writeJSON(filepath.Join(string(dir), manifestFile), m)
}

func digest(g Generated) string {
	g.SourceRef = ""
	raw, _ := canonical(g)
	sum := sha256.Sum256(raw)
	return hex.EncodeToString(sum[:])
}

// Change classifies a regeneration diff for one kind (contract input §22,
// the standard's rule 2): ADDITIVE (a field added, a version bumped) may
// land with the regenerated pair; BREAKING (a field removed or renamed,
// retyped, presence class changed, envelope changed) may not land as "no
// drift" — it needs the deprecation lifecycle (D3), and `check` says so.
type Change struct {
	Kind    string
	Class   string // "additive" | "breaking" | "none"
	Details []string
}

// Classify compares a committed generated file with fresh generation.
func Classify(have, fresh Generated) Change {
	c := Change{Kind: fresh.Kind, Class: "none"}
	hb := map[string]GeneratedField{}
	for _, f := range have.Fields {
		hb[f.Wire] = f
	}
	fb := map[string]GeneratedField{}
	for _, f := range fresh.Fields {
		fb[f.Wire] = f
	}
	breaking := func(d string) { c.Details = append(c.Details, d); c.Class = "breaking" }
	additive := func(d string) {
		c.Details = append(c.Details, d)
		if c.Class == "none" {
			c.Class = "additive"
		}
	}
	if have.Envelope != fresh.Envelope {
		breaking(fmt.Sprintf("envelope %s → %s", have.Envelope, fresh.Envelope))
	}
	if have.Schema != fresh.Schema {
		additive(fmt.Sprintf("schema %s → %s", have.Schema, fresh.Schema))
	}
	for wire, hf := range hb {
		ff, ok := fb[wire]
		switch {
		case !ok:
			breaking("field removed (or renamed — a rename is a remove plus an add): " + wire)
		case hf.GoType != ff.GoType:
			breaking(fmt.Sprintf("field retyped: %s %s → %s", wire, hf.GoType, ff.GoType))
		case hf.Omittable != ff.Omittable:
			breaking(fmt.Sprintf("presence class changed: %s omittable %v → %v", wire, hf.Omittable, ff.Omittable))
		case hf.IsThought != ff.IsThought:
			breaking("thought-ness changed: " + wire)
		}
	}
	for wire := range fb {
		if _, ok := hb[wire]; !ok {
			additive("field added: " + wire)
		}
	}
	return c
}

// Drift compares the committed directory against fresh generation on
// CANONICAL BYTES (source_ref blanked), censuses orphan generated files, and
// checks the manifest. Any line means the contract changed or the directory
// was edited by hand: regenerate and commit in the same change. Where a
// committed file decodes, the change is CLASSIFIED so a breaking source change
// is named as such.
func Drift(dir Dir, fresh []Generated) ([]string, error) {
	var drift []string
	want := map[string]bool{}
	for _, g := range fresh {
		want[g.Kind] = true
		raw, err := os.ReadFile(dir.genPath(g.Kind))
		if err != nil {
			drift = append(drift, fmt.Sprintf("%s: no committed generated file (%v)", g.Kind, err))
			continue
		}
		var have Generated
		if err := decodeStrict(dir.genPath(g.Kind), raw, &have); err != nil {
			drift = append(drift, fmt.Sprintf("%s: %v", g.Kind, err))
			continue
		}
		have.SourceRef = ""
		g2 := g
		g2.SourceRef = ""
		hb, _ := canonical(have)
		fb, _ := canonical(g2)
		// The committed bytes must ALSO be canonical: a hand edit that
		// decodes to the same struct but is not byte-canonical is drift.
		rawBlank := blankSourceRef(raw)
		if !bytes.Equal(hb, fb) || !bytes.Equal(rawBlank, hb) {
			ch := Classify(have, g)
			line := fmt.Sprintf("%s: committed generated contract differs from fresh generation [%s]", g.Kind, ch.Class)
			if len(ch.Details) > 0 {
				line += ": " + strings.Join(ch.Details, "; ")
			}
			if ch.Class == "breaking" {
				line += " — BREAKING: walk the deprecation lifecycle (D3), do not land as a regeneration"
			}
			drift = append(drift, line)
		}
	}
	entries, err := os.ReadDir(string(dir))
	if err != nil {
		return nil, err
	}
	for _, e := range entries {
		n := e.Name()
		if strings.HasSuffix(n, ".generated.json") {
			k := strings.TrimSuffix(n, ".generated.json")
			if !want[k] {
				drift = append(drift, fmt.Sprintf("%s: orphan generated file for an unregistered kind", k))
			}
		}
	}
	mraw, err := os.ReadFile(filepath.Join(string(dir), manifestFile))
	if err != nil {
		drift = append(drift, "MANIFEST.json missing — generation incomplete or never run")
		return drift, nil
	}
	var m Manifest
	if err := decodeStrict(manifestFile, mraw, &m); err != nil {
		drift = append(drift, err.Error())
		return drift, nil
	}
	keys := make([]string, 0, len(m.Kinds))
	for k := range m.Kinds {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	for _, k := range keys {
		if !want[k] {
			drift = append(drift, fmt.Sprintf("MANIFEST lists %s which is not registered", k))
		}
	}
	for _, g := range fresh {
		if m.Kinds[g.Kind] != digest(g) {
			drift = append(drift, fmt.Sprintf("MANIFEST digest for %s does not match fresh generation", g.Kind))
		}
	}
	return drift, nil
}

// blankSourceRef rewrites the source_ref line in committed bytes to the
// blank canonical form so bytes can be compared.
func blankSourceRef(raw []byte) []byte {
	var m map[string]json.RawMessage
	if err := json.Unmarshal(raw, &m); err != nil {
		return raw
	}
	if _, ok := m["source_ref"]; !ok {
		return raw
	}
	var g Generated
	if err := json.Unmarshal(raw, &g); err != nil {
		return raw
	}
	g.SourceRef = ""
	out, _ := canonical(g)
	// only use this if the committed file round-trips exactly through the struct with its own source_ref
	g.SourceRef = ""
	var orig Generated
	_ = json.Unmarshal(raw, &orig)
	origSR := orig.SourceRef
	orig.SourceRef = origSR
	ob, _ := canonical(orig)
	if !bytes.Equal(ob, raw) {
		return raw // not canonical as committed → will not equal hb
	}
	return out
}
