// Package pyargparse is the part of CPython's argparse that this port's
// command-line entry points actually reach: `_parse_known_args` and the
// dozen functions under it.
//
// # Why it is a package
//
// It was written once, inside internal/introspect, for `maro-introspect`.
// The moment a second CLI needed it the choice was to copy 650 lines or to
// extract them, and this port has a standing lesson about that (L14: a
// helper you did not look for is a helper you will write again — the
// byte-wise filename sort was found ALREADY SHIPPED in four packages).
// Copying argparse would have been the worst instance of it available:
// every subtlety below survived a review round somewhere, and a second copy
// starts those rounds over.
//
// # What is here, and what is deliberately not
//
// Here: the two-pass parse (classify every token, then consume left to
// right), option abbreviation on both dash forms, the negative-number
// heuristic, `--` handling, the nargs patterns for optionals and
// positionals, conversion at the point of consumption, and the error
// messages with their exact wording.
//
// Not here: the HelpFormatter. `usage:` and the help body are generated by
// argparse from the parser spec, through a wrapping algorithm keyed to the
// terminal width; each consumer carries its own measured constant instead.
// See the usage constants in the consumers for why that trade was made.
//
// Every behaviour in this file is CPython 3.14's. Where 3.12 differs the
// comment says so, because python3.12 is installed on this box and pyprobe
// invokes bare `python3`.
package pyargparse

import (
	"errors"
	"fmt"
	"math"
	"regexp"
	"strings"
	"unicode/utf8"

	"github.com/slycrel/maro-orchestration/go/internal/pytext"
	"github.com/slycrel/maro-orchestration/go/internal/pyval"
)

// NArgs is argparse's `nargs`, restricted to the forms this port's parsers
// declare. The zero value is Exactly1 rather than "flag" on purpose: an
// option whose NArgs nobody set should misbehave loudly in a test, not
// silently become a flag that swallows nothing.
type NArgs int

const (
	// Exactly1 is nargs=None: one value. `(-*A-*)` for a positional,
	// `([A])` for an optional.
	Exactly1 NArgs = iota
	// Flag is a zero-argument optional (store_true, help): `([AO]{0})`.
	Flag
	// Optional is nargs="?": `(-*A?-*)`.
	Optional
	// OneOrMore is nargs="+": `(-*A[A-]*)`.
	OneOrMore
	// ZeroOrMore is nargs="*": `(-*[A-]*)`.
	ZeroOrMore
)

// Convert is argparse's `_get_value` followed by `_check_value` — the
// `type=` callable and the `choices=` membership test, in that order,
// applied at the point of CONSUMPTION. That timing is observable: an
// invalid value is reported in the order the tokens appeared rather than
// after the whole line is read, so conversion cannot be hoisted out of the
// parse into the caller.
//
// label is the action's name as an error message spells it ("-h/--help"),
// which is why it is passed in rather than closed over.
type Convert func(label, raw string) (any, error)

// Opt is one row of argparse's `_option_string_actions`, which is a dict
// keyed by option STRING — so `-h` and `--help` are two rows sharing one
// action, and that is why both spell their name `-h/--help` in an error
// message. Slice order is the parser's insertion order, because it is the
// order the ambiguity message lists candidates in.
type Opt struct {
	Str   string // the option string as typed
	Dest  string // the namespace key it feeds
	NArgs NArgs  // Flag or Exactly1
	Label string // _get_action_name: every option string of the action
	// Value is what a Flag stores. argparse's store_true stores true;
	// nothing in this port stores a different constant, but naming it
	// keeps store_const reachable without another field.
	Value any
	// Convert runs for an Exactly1 option. nil stores the raw string.
	Convert Convert
	// Help marks argparse's help action, which raises SystemExit — it
	// unwinds the parser from wherever it fired, so nothing later on the
	// line is examined and extras already collected go unreported.
	Help bool
}

// Positional is one positional action, in declaration order.
type Positional struct {
	Dest    string
	NArgs   NArgs
	Label   string
	Convert Convert
	// Required is argparse's `action.required` for a positional, which it
	// computes as `nargs not in ["?", "*"]`. A required positional that
	// matched nothing is reported as "the following arguments are
	// required: <label>" — and that error fires BEFORE the unrecognized-
	// arguments one, because argparse raises it inside _parse_known_args
	// while the extras are reported by parse_args afterwards.
	Required bool
}

// Parser is the subset of ArgumentParser this package models.
type Parser struct {
	// Prog is the name in `prog: error: message`.
	Prog string
	// Usage is the block argparse prints above an error. Generated by
	// HelpFormatter in CPython and a measured constant here.
	Usage       string
	Opts        []Opt
	Positionals []Positional
}

// Result is the argparse Namespace, keyed by dest. A dest absent from the
// map is argparse's default of None — which is a different value from a
// zero, and several call sites branch on the difference.
type Result struct {
	Values map[string]any
	// Help is set when the help action fired. The parse returns no error
	// in that case, matching the SystemExit(0) argparse raises.
	Help bool
}

// Str returns a string-valued dest, or "" when it is absent.
func (r Result) Str(dest string) string {
	if v, ok := r.Values[dest]; ok {
		if s, ok := v.(string); ok {
			return s
		}
	}
	return ""
}

// Strings returns a list-valued dest (nargs "+"/"*"), or nil.
func (r Result) Strings(dest string) []string {
	if v, ok := r.Values[dest]; ok {
		if s, ok := v.([]string); ok {
			return s
		}
	}
	return nil
}

// Bool returns a flag dest.
func (r Result) Bool(dest string) bool {
	if v, ok := r.Values[dest]; ok {
		if b, ok := v.(bool); ok {
			return b
		}
	}
	return false
}

// IntPtr returns an int-valued dest as a pointer, nil when absent —
// argparse's None default for `type=int` with no `default=`.
func (r Result) IntPtr(dest string) *int {
	if v, ok := r.Values[dest]; ok {
		if n, ok := v.(int); ok {
			return &n
		}
	}
	return nil
}

// UsageError is argparse's `parser.error(...)`: usage block on stderr,
// exit 2.
type UsageError struct {
	msg   string
	prog  string
	usage string
}

func (e *UsageError) Error() string { return e.msg }

// Stderr is the whole block argparse writes to STDERR before exiting 2:
// the usage summary, then `prog: error: <message>`. Rendering it here
// rather than at the call site keeps the two halves of the divergence
// together — the code, and the text a script greps for.
func (e *UsageError) Stderr() string {
	return e.usage + e.prog + ": error: " + e.msg + "\n"
}

// ExitStatus maps a parse or Main error onto the (stderr, exit code) pair
// argparse produces. Anything that is not a usage error is not this
// function's to answer.
//
// It exists because there were two copies of that mapping — a command
// wrapper's, and one a differential wrote for itself and then asserted
// against CPython. The test was measuring its own copy.
func ExitStatus(err error) (stderr string, code int, handled bool) {
	if err == nil {
		return "", 0, true
	}
	var ue *UsageError
	if errors.As(err, &ue) {
		return ue.Stderr(), 2, true
	}
	return "", 0, false
}

func (p *Parser) errorf(format string, a ...any) error {
	return &UsageError{msg: fmt.Sprintf(format, a...), prog: p.Prog, usage: p.Usage}
}

// Errorf builds a UsageError carrying this parser's prog and usage, for a
// consumer that has to refuse something the parse itself cannot see.
func (p *Parser) Errorf(format string, a ...any) error {
	return p.errorf(format, a...)
}

// How an explicit argument was attached to an option string. argparse keeps
// these three states apart and BRANCHES on the difference: `--latest=x` (an
// equals sign) is always an error on a flag, while `-hx` (glued to a
// single-dash option) is argparse re-reading the tail as more single-dash
// options. A port that collapsed them would reject `-hx`, which prints help.
const (
	sepNone   = iota // no explicit argument at all
	sepConcat        // glued to a single-dash option: `-hx`
	sepEquals        // `--history=5`
)

// optTuple is one candidate reading of a token: which option it names, which
// option string matched (an abbreviation resolves to the full one), and any
// argument attached to it.
type optTuple struct {
	opt      int // index into Parser.Opts, or -1 for an unknown option
	str      string
	sep      int
	explicit string
}

// negativeNumber is argparse's `_negative_number_matcher`, and it is NOT the
// anchored pattern it looks like it should be. CPython 3.14 spells it
// `-\.?\d` and applies it with `.match`, which anchors only at the START —
// so every token beginning with a dash and a digit is a positional, not just
// the ones that are entirely numeric. `-1latest` is a positional.
//
// `\d` in a Python str pattern is Unicode-aware, so an Arabic-Indic digit
// counts; Go's `\d` is ASCII-only, hence the explicit category class.
//
// Version-dependent, and the boundary is not where a reader would guess.
// Measured on this box: python3.12 still carries `^-\d+$|^-\d*\.\d+$`,
// anchored at both ends, under which `-1latest`, `-.5` and `-٥` are all
// unrecognized arguments. python3.14 carries `-\.?\d` applied with `.match`.
// The change landed in 3.13. If a differential ever goes red on the
// negative-number cases, check `python3 --version` before checking the code.
var negativeNumber = regexp.MustCompile(`^-\.?[\p{Nd}]`)

// parseOptional is argparse's `_parse_optional`: given one token, either nil
// (it is a positional) or the candidate options it could be naming. It never
// reports an error — ambiguity is raised later, by the consumer.
func (p *Parser) parseOptional(arg string) []optTuple {
	if arg == "" || arg[0] != '-' {
		return nil
	}
	for i, o := range p.Opts {
		if o.Str == arg {
			return []optTuple{{opt: i, str: arg, sep: sepNone}}
		}
	}
	// A lone "-" is a positional. It is also, once consumed as a value, an
	// invalid int rather than a missing argument.
	if len(arg) == 1 {
		return nil
	}
	// An exact option string before the `=`. This block is LOAD-BEARING:
	// `-h=x` is exact here and comes out sepEquals, which is what makes the
	// consumer refuse it. Delete the block and the same token resolves
	// through optionTuples' single-dash arm as sepConcat instead, and a
	// refusal turns into a help screen.
	if before, after, found := strings.Cut(arg, "="); found {
		for i, o := range p.Opts {
			if o.Str == before {
				return []optTuple{{opt: i, str: before, sep: sepEquals, explicit: after}}
			}
		}
	}
	if tuples := p.optionTuples(arg); len(tuples) > 0 {
		return tuples
	}
	if negativeNumber.MatchString(arg) {
		return nil
	}
	// argparse's own comment: "if it contains a space, it was meant to be a
	// positional".
	if strings.Contains(arg, " ") {
		return nil
	}
	return []optTuple{{opt: -1, str: arg, sep: sepNone}}
}

// optionTuples is argparse's `_get_option_tuples` — the abbreviation rule,
// which works differently on the two dash forms.
//
// A double-dash token is a PREFIX of a long option: `--lat` is `--latest`,
// `--l` is ambiguous between latest and lenses. A single-dash token instead
// offers its first two characters as a whole option and the rest as a glued
// argument, which is how `-hx` reaches the help action.
func (p *Parser) optionTuples(arg string) []optTuple {
	var out []optTuple
	if len(arg) >= 2 && arg[1] == '-' {
		prefix, explicit, found := strings.Cut(arg, "=")
		sep := sepNone
		if !found {
			explicit = ""
		} else {
			sep = sepEquals
		}
		for i, o := range p.Opts {
			if strings.HasPrefix(o.Str, prefix) {
				out = append(out, optTuple{opt: i, str: o.Str, sep: sep, explicit: explicit})
			}
		}
		return out
	}
	// Both halves of the single-dash arm cut on `=`, and they cut for
	// different reasons. The abbreviation test is against the part BEFORE the
	// `=` — not the whole token — which is how `-=x` matches every option in
	// the table (they all start with `-`) and comes out ambiguous rather than
	// unrecognized. The glued-argument test is against the first two code
	// points regardless of any `=`.
	prefix, explicit, found := strings.Cut(arg, "=")
	sep := sepNone
	if found {
		sep = sepEquals
	} else {
		explicit = ""
	}
	// EQUIVALENT MUTANT (measured): cutting by BYTES here — `arg[:2]` —
	// passes the whole corpus. A byte cut differs from a code-point cut
	// only when arg's second character is multi-byte, and the resulting
	// prefix is then invalid UTF-8, which can never equal an option
	// string: every option in this port's parsers is ASCII. The rune cut
	// stays because `option_string[:2]` is what argparse does and the
	// next parser to declare a non-ASCII option would silently get the
	// wrong answer from the byte version.
	shortPrefix, shortExplicit := cutRunes(arg, 2)
	for i, o := range p.Opts {
		switch {
		case o.Str == shortPrefix:
			out = append(out, optTuple{opt: i, str: o.Str,
				sep: sepConcat, explicit: shortExplicit})
		case strings.HasPrefix(o.Str, prefix):
			out = append(out, optTuple{opt: i, str: o.Str,
				sep: sep, explicit: explicit})
		}
	}
	return out
}

// cutRunes splits s after its first n code points. Python slices strings by
// code point, so `option_string[:2]` of `-٥x` is the dash and the digit —
// where a byte slice would cut the digit in half.
func cutRunes(s string, n int) (string, string) {
	i := 0
	for ; n > 0 && i < len(s); n-- {
		_, w := utf8.DecodeRuneInString(s[i:])
		i += w
	}
	return s[:i], s[i:]
}

// firstRune splits s into its first code point and the rest, the pair
// argparse spells `explicit_arg[0]` and `explicit_arg[1:]`.
func firstRune(s string) (string, string) { return cutRunes(s, 1) }

// runeAt is `s[i]` by code point, or "" if s is shorter. argparse tests
// `option_string[1]` to tell a single-dash option from a double-dash one.
func runeAt(s string, i int) string {
	_, rest := cutRunes(s, i)
	first, _ := cutRunes(rest, 1)
	return first
}

// nargsPattern is `_get_nargs_pattern`. The optional forms have no `-` in
// them at ALL, which is why `--history -- 5` is a missing argument rather
// than 5: the terminator classifies as '-', which the stripped pattern
// cannot consume — and so are `--history --tory` and `--history -x`, which
// classify as 'O'.
//
// HOW 3.14 yields the optional forms differs from earlier versions: it
// selects `'([A])' if option else '(-*A-*)'` directly, and `'([AO]{0})'`
// for a zero-nargs optional. Through 3.12 the positional pattern was built
// first and then stripped with two `.replace` calls. Same result for these
// nargs; a different mechanism.
func nargsPattern(n NArgs, option bool) string {
	if option {
		switch n {
		case Flag:
			return "([AO]{0})"
		default:
			return "([A])"
		}
	}
	switch n {
	case Optional:
		return "(-*A?-*)"
	case OneOrMore:
		return "(-*A[A-]*)"
	case ZeroOrMore:
		return "(-*[A-]*)"
	default:
		return "(-*A-*)"
	}
}

// errHelpAction stands in for the SystemExit argparse's help action raises.
var errHelpAction = errors.New("help action")

// actionTuple is one entry of argparse's `action_tuples` — an action and the
// strings it consumed, held until the whole option token is understood.
type actionTuple struct {
	opt  int
	args []string
}

// parseState is the local state of `_parse_known_args`: the classification
// string, the options found in it, the positionals still unfilled, and the
// tokens nothing claimed.
type parseState struct {
	p       *Parser
	argv    []string
	pattern []byte // one byte per token: 'A', 'O', or '-'
	optIdx  map[int][]optTuple
	extras  []string

	posLeft []Positional
	seen    map[string]bool
	res     Result
}

// Parse is `parser.parse_args(argv)`.
//
// Two passes, because argparse takes two: every token is classified first,
// and only then are they consumed left to right. The order is observable.
// Classification never fails, so `--bogus -h` prints help instead of
// complaining, and `-h --l` prints help even though `--l` is ambiguous —
// while `--l -h` is an error, because consumption reaches the ambiguity
// first. An unrecognized option is not an error where it appears either: it
// is set aside and reported at the very end, after any error the rest of the
// line produces.
func (p *Parser) Parse(argv []string) (Result, error) {
	st := &parseState{
		p:       p,
		argv:    argv,
		pattern: make([]byte, len(argv)),
		optIdx:  map[int][]optTuple{},
		posLeft: append([]Positional(nil), p.Positionals...),
		seen:    map[string]bool{},
		res:     Result{Values: map[string]any{}},
	}
	err := st.parse()
	if errors.Is(err, errHelpAction) {
		// The help action is a SystemExit in CPython — it unwinds the parser
		// from wherever it fired, which is why nothing later on the line is
		// examined and why extras already collected go unreported.
		st.res.Help = true
		return st.res, nil
	}
	return st.res, err
}

func (s *parseState) parse() error {
	// Pass one: classify every token. argparse builds a STRING of one
	// character per token and every later decision matches against that
	// string rather than against the tokens themselves.
	terminated := false
	for i, arg := range s.argv {
		switch {
		case terminated:
			s.pattern[i] = 'A'
		case arg == "--":
			// Only the FIRST `--` is the terminator. A second one after it is
			// an ordinary positional — handled by the `terminated` arm ABOVE
			// this one, so adding `&& !terminated` here would be dead code
			// (it was tried as a mutation and could not change an answer).
			s.pattern[i] = '-'
			terminated = true
		default:
			if t := s.p.parseOptional(arg); t != nil {
				s.pattern[i], s.optIdx[i] = 'O', t
			} else {
				s.pattern[i] = 'A'
			}
		}
	}

	// Pass two: alternate between the positionals preceding the next option
	// and the option itself, left to right.
	maxOption := -1
	for i := range s.optIdx {
		if i > maxOption {
			maxOption = i
		}
	}
	start := 0
	for start <= maxOption {
		nextOption := start
		for nextOption <= maxOption {
			if _, ok := s.optIdx[nextOption]; ok {
				break
			}
			nextOption++
		}
		if start != nextOption {
			end, err := s.consumePositionals(start)
			if err != nil {
				return err
			}
			if end > start {
				start = end
				continue
			}
			start = end
		}
		if _, ok := s.optIdx[start]; !ok {
			// Positionals nothing could take. They are set aside rather than
			// refused here, and reported at the very end.
			s.extras = append(s.extras, s.argv[start:nextOption]...)
			start = nextOption
		}
		var err error
		if start, err = s.consumeOptional(start); err != nil {
			return err
		}
	}

	stop, err := s.consumePositionals(start)
	if err != nil {
		return err
	}
	s.extras = append(s.extras, s.argv[stop:]...)

	// Required actions are reported from INSIDE _parse_known_args, so this
	// fires before the unrecognized-arguments error that parse_args raises
	// afterwards. `maro-run --bogus` with no goal names the missing goal,
	// not the bogus option.
	var missing []string
	for _, pos := range s.p.Positionals {
		if pos.Required && !s.seen[pos.Dest] {
			missing = append(missing, pos.Label)
		}
	}
	if len(missing) > 0 {
		return s.p.errorf("the following arguments are required: %s",
			strings.Join(missing, ", "))
	}

	if len(s.extras) > 0 {
		return s.p.errorf("unrecognized arguments: %s", strings.Join(s.extras, " "))
	}
	return nil
}

// consumeOptional is argparse's function of the same name. One token can name
// SEVERAL actions — `-hh` is `-h -h` — so it loops, collecting actions and
// re-reading the tail, and takes none of them until the token is fully
// understood. That deferral is observable: `-hh=x` collects one help action
// and then refuses the `=x`, so it exits 2 instead of printing help.
func (s *parseState) consumeOptional(startIndex int) (int, error) {
	tuples := s.optIdx[startIndex]
	if len(tuples) > 1 {
		names := make([]string, len(tuples))
		for j, t := range tuples {
			names[j] = t.str
		}
		// The message names the token AS TYPED, not the prefix it was cut
		// down to, so `--=x` reports `--=x` and lists every long option it
		// could have meant.
		return 0, s.p.errorf("ambiguous option: %s could match %s",
			s.argv[startIndex], strings.Join(names, ", "))
	}
	t := tuples[0]
	opt, optionString, sep, explicit := t.opt, t.str, t.sep, t.explicit
	// `explicit_arg is not None` is a different question from whether it is
	// empty: `--latest=` HAS an explicit argument, the empty string, and
	// argparse refuses it.
	hasExplicit := sep != sepNone

	var actions []actionTuple
	stop := 0
loop:
	for {
		if opt < 0 {
			// No action matched. The token is set aside whole and reported at
			// the end, after any error the rest of the line produces.
			s.extras = append(s.extras, s.argv[startIndex])
			return startIndex + 1, nil
		}
		o := s.p.Opts[opt]

		if !hasExplicit {
			// No glued argument, so the values are the FOLLOWING tokens.
			b := startIndex + 1
			n, err := s.matchArgument(o, s.pattern[b:])
			if err != nil {
				return 0, err
			}
			stop = b + n
			actions = append(actions, actionTuple{opt: opt, args: s.argv[b:stop]})
			break loop
		}

		argCount := 0
		if o.NArgs != Flag {
			argCount = 1
		}
		switch {
		case argCount == 0 && runeAt(optionString, 1) != "-" && explicit != "":
			// A single-dash flag with a tail. argparse re-reads the tail as
			// more single-dash options — this is why `-hh` is `-h -h` — but
			// only when the tail could BE options: an `=` separator, or a
			// leading dash, means the user meant it as a value, and a value
			// is what a flag cannot take.
			//
			// Python's `sep` is '' for a glued tail and '=' for an explicit
			// one, so its `if sep or ...` tests for the `=` form alone. The
			// constants here are numbers and would ALL be truthy, so the test
			// has to name the case.
			head, tail := firstRune(explicit)
			if sep == sepEquals || head == "-" {
				return 0, s.p.errorf("argument %s: ignored explicit argument %s",
					o.Label, pyval.Repr(explicit))
			}
			actions = append(actions, actionTuple{opt: opt})
			dash, _ := firstRune(optionString)
			optionString = dash + head
			next := s.p.lookupOption(optionString)
			if next < 0 {
				// The tail names no option: it joins the extras whole, and
				// the actions collected so far still run. `-hx` prints help
				// and never reports the `-x`.
				s.extras = append(s.extras, dash+explicit)
				stop = startIndex + 1
				break loop
			}
			opt, explicit = next, tail
			switch {
			case explicit == "":
				sep, hasExplicit = sepNone, false
			case strings.HasPrefix(explicit, "="):
				sep = sepEquals
				_, explicit = firstRune(explicit)
			default:
				sep = sepConcat
			}
		case argCount == 1:
			// The glued text IS the value: `--history=5`.
			stop = startIndex + 1
			actions = append(actions, actionTuple{opt: opt, args: []string{explicit}})
			break loop
		default:
			return 0, s.p.errorf("argument %s: ignored explicit argument %s",
				o.Label, pyval.Repr(explicit))
		}
	}

	for _, at := range actions {
		if err := s.takeOptional(at); err != nil {
			return 0, err
		}
	}
	return stop, nil
}

// matchArgument is `_match_argument` for the two optional nargs this port
// declares.
func (s *parseState) matchArgument(o Opt, pattern []byte) (int, error) {
	if o.NArgs == Flag {
		return 0, nil
	}
	if len(pattern) == 0 || pattern[0] != 'A' {
		return 0, s.p.errorf("argument %s: expected one argument", o.Label)
	}
	return 1, nil
}

// consumePositionals is argparse's function of the same name, over however
// many positionals remain.
//
// The trailing `-*` in the nargs patterns is why the terminator cannot
// simply be dropped. `--` is removed only when a positional's matched span
// COVERS it, so `a -- b` matches "A-" and reports `unrecognized arguments:
// b`, while `a b -- c` matches only "A" and reports `b -- c` — terminator
// included. A port that skipped every `--` unconditionally disagrees with
// CPython on the whole second shape.
func (s *parseState) consumePositionals(startIndex int) (int, error) {
	counts := s.matchPartial(s.posLeft, string(s.pattern[startIndex:]))
	for i, n := range counts {
		pos := s.posLeft[i]
		args := append([]string(nil), s.argv[startIndex:startIndex+n]...)
		// `args.remove('--')` — the first occurrence only, and only when
		// the matched span contains one.
		for j, a := range args {
			if a == "--" {
				args = append(args[:j:j], args[j+1:]...)
				break
			}
		}
		startIndex += n
		if err := s.takePositional(pos, args); err != nil {
			return 0, err
		}
	}
	s.posLeft = s.posLeft[len(counts):]
	return startIndex, nil
}

// matchPartial is `_match_arguments_partial`: try the first i positionals
// for i from len down to 1, and take the first combined pattern that
// matches at the START of the remaining classification string.
func (s *parseState) matchPartial(positionals []Positional, pattern string) []int {
	for i := len(positionals); i > 0; i-- {
		var sb strings.Builder
		for _, pos := range positionals[:i] {
			sb.WriteString(nargsPattern(pos.NArgs, false))
		}
		re, err := regexp.Compile("^" + sb.String())
		if err != nil {
			continue
		}
		if m := re.FindStringSubmatch(pattern); m != nil {
			out := make([]int, 0, i)
			for _, g := range m[1:] {
				out = append(out, len(g))
			}
			return out
		}
	}
	return nil
}

// takeOptional runs one collected option action. argparse converts a value
// here, at the point of consumption, so an invalid value is reported in the
// order the tokens appeared rather than after the whole line is read.
func (s *parseState) takeOptional(at actionTuple) error {
	o := s.p.Opts[at.opt]
	s.seen[o.Dest] = true
	if o.Help {
		s.res.Values[o.Dest] = true
		return errHelpAction
	}
	if o.NArgs == Flag {
		v := o.Value
		if v == nil {
			v = true
		}
		s.res.Values[o.Dest] = v
		return nil
	}
	raw := ""
	if len(at.args) > 0 {
		raw = at.args[0]
	}
	if o.Convert == nil {
		s.res.Values[o.Dest] = raw
		return nil
	}
	v, err := o.Convert(o.Label, raw)
	if err != nil {
		return s.convertErr(err)
	}
	s.res.Values[o.Dest] = v
	return nil
}

// takePositional stores a positional's matched span. A positional that
// matched NOTHING is still consumed — that is what makes a second bare
// token an extra rather than a second value — but it does not count as
// SEEN, which is what the required check reads.
func (s *parseState) takePositional(pos Positional, args []string) error {
	multi := pos.NArgs == OneOrMore || pos.NArgs == ZeroOrMore
	// Unconditional, because argparse's take_action does
	// `seen_actions.add(action)` before it looks at the values, and the
	// required check reads seen_actions. A guard on len(args) was here
	// first and NO INPUT distinguishes the two: a required positional is
	// `nargs not in ["?", "*"]`, and every other nargs needs at least one
	// 'A' to match at all, so a required positional can never be taken
	// with an empty span. The rule is written argparse's way anyway —
	// an unobservable difference is still a wrong rule for the next
	// parser spec to trip over.
	s.seen[pos.Dest] = true
	if multi {
		if len(args) == 0 && pos.NArgs == OneOrMore {
			// An empty match for "+" cannot happen: the pattern requires
			// one 'A'. ZeroOrMore stores its empty list.
			return nil
		}
		if pos.Convert == nil {
			s.res.Values[pos.Dest] = args
			return nil
		}
		out := make([]any, 0, len(args))
		for _, a := range args {
			v, err := pos.Convert(pos.Label, a)
			if err != nil {
				return s.convertErr(err)
			}
			out = append(out, v)
		}
		s.res.Values[pos.Dest] = out
		return nil
	}
	if len(args) == 0 {
		return nil
	}
	if pos.Convert == nil {
		s.res.Values[pos.Dest] = args[0]
		return nil
	}
	v, err := pos.Convert(pos.Label, args[0])
	if err != nil {
		return s.convertErr(err)
	}
	s.res.Values[pos.Dest] = v
	return nil
}

// convertErr re-homes a Convert's error onto this parser, so a consumer can
// build its message with Errorf-free helpers and still get the right prog
// and usage block in front of it.
func (s *parseState) convertErr(err error) error {
	var ue *UsageError
	if errors.As(err, &ue) {
		return &UsageError{msg: ue.msg, prog: s.p.Prog, usage: s.p.Usage}
	}
	return err
}

// lookupOption is the `option_string in self._option_string_actions` test.
func (p *Parser) lookupOption(s string) int {
	for i, o := range p.Opts {
		if o.Str == s {
			return i
		}
	}
	return -1
}

// IntValue is argparse's `type=int`: `_get_value` calls int() and reports
// the failure as `invalid int value: <repr>`.
//
// Python ints are arbitrary precision, so forty digits is a perfectly good
// (enormous) value there and an overflow here. Saturating rather than
// refusing keeps the BEHAVIOUR identical wherever the consumer only
// compares the number, and inventing a refusal CPython does not make is
// the one thing a port must not do with an out-of-range literal.
func IntValue(label, raw string) (any, error) {
	n, err := pyval.Int(raw)
	if err == nil {
		return n, nil
	}
	if !errors.Is(err, pyval.ErrIntTooLarge) {
		return nil, &UsageError{msg: fmt.Sprintf(
			"argument %s: invalid int value: %s", label, pyval.Repr(raw))}
	}
	if strings.HasPrefix(pytext.Strip(raw), "-") {
		return math.MinInt, nil
	}
	return math.MaxInt, nil
}

// Choices is argparse's `_check_value`, which runs AFTER `_get_value` and
// reports membership failure as
//
//	argument <label>: invalid choice: <repr> (choose from a, b, c)
//
// Measured on CPython 3.14.3: the choices in that list are NOT quoted.
// Through 3.11 they were (`choose from 'a', 'b'`), so a port checked
// against an older interpreter disagrees here for a reason that has
// nothing to do with this code.
func Choices(allowed ...string) Convert {
	return func(label, raw string) (any, error) {
		for _, a := range allowed {
			if a == raw {
				return raw, nil
			}
		}
		return nil, &UsageError{msg: fmt.Sprintf(
			"argument %s: invalid choice: %s (choose from %s)",
			label, pyval.Repr(raw), strings.Join(allowed, ", "))}
	}
}
