#!/usr/bin/env python3
"""Regenerate go/PORT_STATUS.md — which Python modules the Go tree claims.

The standing goal for this arc is "the first pass of the go port
completely implemented", so the denominator is load-bearing. It was wrong
for three weeks: PORT.md's scope ledger reported "23 modules, ~26,800
lines" remaining, which was the remaining count among the 59 modules its
table listed. The table had a ~690-line display cut-off that quietly
started reading as a scoping claim, and the 124 modules under it were in
neither the numerator nor the denominator.

So this is generated, not written. A hand-maintained denominator is worth
nothing, and this one has already proven it.

WHAT IT MEASURES: a production (non-_test) .go file naming the Python
source file. That is a declaration the port's own source makes — package
docs name what they port — which is why it regenerates rather than drifts.

WHAT IT DOES NOT: it is not a completeness claim. `heartbeat.py`,
`sheriff.py` and `system_health.py` are each ported to "deterministic half
done, orchestration half NAMED", and read here identically to a module
ported end to end. It also cannot see a module ported without being named,
though that direction was checked and no module is currently missed by it.

Usage:
    python3 go/tools/port-status.py            # rewrite go/PORT_STATUS.md
    python3 go/tools/port-status.py --check    # exit 1 if it would change
"""

import argparse
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
GO_ROOT = os.path.dirname(HERE)
REPO_ROOT = os.path.dirname(GO_ROOT)
OUT = os.path.join(GO_ROOT, "PORT_STATUS.md")

# The source of truth is the mainline checkout, not this worktree: a port
# branch must not be able to change its own denominator by editing Python.
SRC_CANDIDATES = [
    os.path.join(REPO_ROOT, "src"),
    "/home/clawd/claude/maro-orchestration/src",
]

PREAMBLE = """\
# Port status — which Python modules the Go tree claims

Generated by `tools/port-status.py`. Regenerate it rather than editing it
by hand; the numbers here are the denominator the standing goal ("the
first pass of the go port completely implemented") is measured against,
and a hand-edited denominator is worth nothing.

## What this measures, and what it does not

A row is here because a **production** `.go` file in this module names the
Python source — the port's convention is that a package's doc comment
names what it ports. That is a DECLARATION made by the port's own source,
which is why it can be regenerated and cannot drift silently.

It is not a claim that the module is finished. Several rows are ported to
the standard this arc calls *scoped*: the deterministic half ported, the
orchestration or LLM half NAMED in the package doc as not-ported
(`heartbeat.py`, `sheriff.py`, `system_health.py` are the three that say
so out loud). Others are named only because one function of theirs was
needed. Read a row as "the port has an opinion about this module", not as
"done".

It also cannot see a module ported without being named, and that blind
spot is REAL AND UNQUANTIFIED. This paragraph previously claimed that
`killswitch`, `ancestry`, `prefixes` and `security` "also appear by
filename somewhere, so none of them is missed here". Measured 2026-08-27:
none of the four appears by filename in any production `.go` file, and
all four sit in the undeclared queue below. They are EXAMPLES of the
blind spot, not counterexamples to it — a bare `killswitch` in
`internal/provenance` tells this scan nothing.

So read the undeclared queue as "no declaration either way", never as
"not started". Closing the gap means naming the source file in the
package doc, which is the convention already, or judging the row by hand.
(An enumeration can be wrong at BIRTH — this file exists because one was,
and its own preamble then was too, one chunk later.)

## Why this file exists

`PORT.md`'s scope ledger reported the remaining surface as "23 modules,
~26,800 lines" for three weeks. That was the remaining count among the 59
modules its table listed — the table has a size cut-off at ~690 lines that
was a display decision — while the Python surface is **{total_mods}
modules, {total_lines:,} lines**. The modules under the cut were not in the
burndown at all in either direction. An enumeration can be wrong at BIRTH,
and this one was: the cut-off was never a scoping claim, it just started
reading like one.

## The declared surface

"""

TAIL = """
Undeclared is not the same as untouched — this list is UNJUDGED, and
judging it is the work this file makes possible rather than the work it
does. Some of these are dev tooling by decree (`correspondence.py`), some
are pure LLM/network surfaces whose port is an adapter call, and some are
simply not started. Until each row carries a declared status, the honest
statement about the port's completeness is:

> **{have_mods} of {total_mods} modules ({have_lines:,} of {total_lines:,}
> lines, {pct}%) are named by a Go production package. The other
> {none_mods} have no declaration either way.**

That is a lower bound on progress with a known gap above it, which is
strictly better than the single number it replaces.
"""


def src_dir():
    for d in SRC_CANDIDATES:
        if os.path.isdir(d):
            return d
    sys.exit("no src/ found; looked in %s" % ", ".join(SRC_CANDIDATES))


def line_count(path):
    with open(path, encoding="utf-8", errors="replace") as fh:
        return sum(1 for _ in fh)


def declarations(mods):
    """module -> {go package dir} for every production .go file naming it."""
    found = {}
    # Compiled once: 183 patterns against every file is the difference
    # between a second and a minute on this box.
    pats = {m: re.compile(r"\b" + re.escape(m) + r"\b") for m in mods}
    for dirpath, dirnames, files in os.walk(GO_ROOT):
        dirnames[:] = [d for d in dirnames if d != ".git"]
        for fn in files:
            if not fn.endswith(".go") or fn.endswith("_test.go"):
                continue
            p = os.path.join(dirpath, fn)
            with open(p, encoding="utf-8", errors="replace") as fh:
                text = fh.read()
            pkg = os.path.relpath(os.path.dirname(p), GO_ROOT)
            for m, pat in pats.items():
                if pat.search(text):
                    found.setdefault(m, set()).add(pkg)
    return found


def render():
    src = src_dir()
    mods = sorted(f for f in os.listdir(src) if f.endswith(".py"))
    if not mods:
        sys.exit("no .py modules in %s; refusing to write an empty ledger" % src)
    lines = {m: line_count(os.path.join(src, m)) for m in mods}
    named = declarations(mods)

    have = sorted(((m, lines[m], sorted(named[m])) for m in mods if m in named),
                  key=lambda r: -r[1])
    none = sorted(((m, lines[m]) for m in mods if m not in named),
                  key=lambda r: -r[1])

    total_mods, total_lines = len(mods), sum(lines.values())
    have_lines = sum(r[1] for r in have)
    none_lines = sum(r[1] for r in none)

    out = [PREAMBLE.format(total_mods=total_mods, total_lines=total_lines)]
    out.append("| Python module | lines | named by (Go production package) |\n")
    out.append("|---|---:|---|\n")
    for m, n, pkgs in have:
        out.append("| `%s` | %d | %s |\n"
                   % (m, n, ", ".join("`" + p + "`" for p in pkgs)))
    out.append("\n**%d modules / %d lines** carry a declaration. "
               "**%d modules / %d lines** do not.\n"
               % (len(have), have_lines, len(none), none_lines))
    out.append("\n### The undeclared queue — %d modules, %d lines, UNJUDGED\n\n"
               % (len(none), none_lines))
    out.append("| Python module | lines |\n")
    out.append("|---|---:|\n")
    for m, n in none:
        out.append("| `%s` | %d |\n" % (m, n))
    out.append(TAIL.format(
        have_mods=len(have), total_mods=total_mods,
        have_lines=have_lines, total_lines=total_lines,
        pct=round(100.0 * have_lines / total_lines),
        none_mods=len(none)))
    return "".join(out)


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true",
                    help="exit 1 if PORT_STATUS.md would change")
    args = ap.parse_args()

    want = render()
    if args.check:
        try:
            with open(OUT, encoding="utf-8") as fh:
                got = fh.read()
        except FileNotFoundError:
            sys.exit("PORT_STATUS.md does not exist; run without --check")
        if got != want:
            sys.exit("PORT_STATUS.md is stale — run "
                     "`python3 go/tools/port-status.py`")
        print("PORT_STATUS.md is current")
        return
    with open(OUT, "w", encoding="utf-8") as fh:
        fh.write(want)
    print("wrote %s" % OUT)


if __name__ == "__main__":
    main()
