"""Dev-status readout — where the project actually is, recomputed on demand.

Jeremy, 2026-08-16, on why this exists: *"I'm often trapped with less
visibility in where we actually are at the high level and end up in an
'ok, keep implementing' sort of loop… I'm less worried about the number
of checkboxes, and more interested in meaningful progress, which
sometimes seems elusive."*

The diagnosis behind the design: **the backlog is a findings log, and its
job is to grow.** Judging progress by open-checkbox count guarantees the
feeling of going nowhere no matter how well things go — which is why
archiving it twice and running "finish unfinished items" sessions did not
help. Those optimize a metric that structurally cannot improve. So this
readout leads with the capability ledger (what the system can provably
DO, `docs/CAPABILITIES.md` under the claimed≠probed rule) and reports the
backlog as a rate, not a total.

**It also has to guard against itself, and that is not decoration.** The
first cut of these numbers was produced by grepping bare words out of
CAPABILITIES.md, which counted prose — including the paragraph that
DEFINES the three marks — and reported 42 verified where the row-level
truth was 19. It made a flat trend look like 3x convergence, and that
wrong number was reported before anyone caught it. Two consequences are
built in here: marks are parsed only in the shapes that carry a status
CLAIM (a table cell, a `status:` annotation), never as free text; and the
readout always prints how stale the ledger itself is, because a flat line
from an unmaintained doc and a flat line from stalled work are the same
picture and must never render the same way.

Recompute posture (Jeremy left the call here): on demand, and printed
after every land. It deliberately does NOT run on a timer — a cron that
recomputes when nothing changed is noise, and this repo's standing
posture is observational instruments, never enforcement. `--write` folds
the block into `docs/DEV_LOG.md` between markers; land.sh prints the
one-line summary and says when the written block has gone stale, rather
than silently dirtying a shared working tree (CLAUDE.md concurrency
rule 3 — a tracked file changed by a hook is a stranger in someone
else's `git status`).
"""

from __future__ import annotations

import re
import subprocess
from dataclasses import dataclass, field
from pathlib import Path
from typing import Callable, Dict, List, Optional

MARKS = ("verified", "target", "aspirational")

BLOCK_START = "<!-- dev-status: generated by `maro dev-status --write`, do not hand-edit -->"
BLOCK_END = "<!-- /dev-status -->"

# An arc that never says what would make it stop is the shape that runs
# rounds 13 through 17. These are the phrasings this repo actually uses
# when it declares one.
_STOP_RULE_MARKERS = (
    "kill criterion", "kill-criterion", "falsifier", "stop criteria",
    "revisit trigger", "evidence-gated", "gated on", "watch-item",
    "abandon if", "drop it if",
)


# ---------------------------------------------------------------------------
# Parsing — pure, so the tests can hold it to shapes rather than to a corpus
# ---------------------------------------------------------------------------

def capability_marks(text: str) -> Dict[str, int]:
    """Row-level status marks in CAPABILITIES.md.

    Only two shapes carry a status CLAIM: a table cell that begins with
    the backticked mark, and a `status: \\`mark\\`` annotation. Free-text
    mentions are excluded by construction — the grounding-rule paragraph
    that defines all three words would otherwise inflate every count, and
    did.
    """
    counts = {m: 0 for m in MARKS}
    fenced = False
    for line in text.splitlines():
        # A fenced block is documentation OF the format, not a claim in it.
        # A doc that shows an example row inside ``` was counting that
        # example as a real capability — the same count-the-explanation
        # failure as the grounding paragraph (minimalist lens, 2026-08-16).
        if line.lstrip().startswith("```"):
            fenced = not fenced
            continue
        if fenced:
            continue
        claimed = False
        if line.lstrip().startswith("|") and line.count("|") >= 3:
            for cell in (c.strip() for c in line.split("|")):
                m = re.match(r"^\*{0,2}`(verified|target|aspirational)`", cell)
                if m:
                    counts[m.group(1)] += 1
                    claimed = True
                    break          # one mark per row, the leftmost wins
        # The `status:` shape is for prose/blockquote rows. It used to run
        # unconditionally, so a table row whose notes cell QUOTED a status
        # ("status: `verified` was the old call, now target") counted twice —
        # the same over-count-from-surrounding-prose class this parser was
        # written to prevent, just one level in (review, 2026-08-16).
        if claimed:
            continue
        for m in re.finditer(r"status:\s*`(verified|target|aspirational)`", line):
            counts[m.group(1)] += 1
    return counts


@dataclass
class BacklogState:
    """The backlog split into the three things it actually contains.

    Reading it as one list is the visibility bug: live work, shipped
    records and evidence-gated watch-items look identical on the page.
    """

    open_boxes: int = 0
    checked_boxes: int = 0
    entries_live: int = 0        # has open work
    entries_record: int = 0      # no checkboxes at all — narrative
    entries_gated: int = 0       # open work, but waiting on evidence
    entries_no_stop_rule: List[str] = field(default_factory=list)


def backlog_state(text: str, section_filter: str = "Actionable") -> BacklogState:
    """Census one section of BACKLOG.md."""
    st = BacklogState()
    section = ""
    cur_title = None
    cur_open = cur_checked = 0
    cur_body: List[str] = []

    def flush():
        nonlocal cur_title, cur_open, cur_checked, cur_body
        if cur_title is None:
            return
        blob = (cur_title + "\n" + "\n".join(cur_body)).lower()
        gated = any(k in blob for k in _STOP_RULE_MARKERS)
        if cur_open:
            st.entries_live += 1
            if gated:
                st.entries_gated += 1
            else:
                st.entries_no_stop_rule.append(cur_title[:70])
        elif not cur_checked:
            st.entries_record += 1
        cur_title, cur_open, cur_checked, cur_body = None, 0, 0, []

    for line in text.splitlines():
        if line.startswith("## "):
            flush()
            section = line[3:].strip()
        elif line.startswith("### "):
            flush()
            if section_filter in section:
                cur_title = line[4:].strip()
        elif cur_title is not None:
            cur_body.append(line)
            if re.match(r"\s*- \[ \]", line):
                cur_open += 1
                st.open_boxes += 1
            elif re.match(r"\s*- \[x\]", line):
                cur_checked += 1
                st.checked_boxes += 1
    flush()
    return st


# ---------------------------------------------------------------------------
# Git-backed history — injected so tests never shell out
# ---------------------------------------------------------------------------

def _git(repo: Path) -> Callable[[List[str]], str]:
    def run(args: List[str]) -> str:
        try:
            return subprocess.run(["git", "-C", str(repo)] + args,
                                  capture_output=True, text=True,
                                  timeout=30).stdout.strip()
        except (OSError, subprocess.SubprocessError):
            return ""
    return run


@dataclass
class Trend:
    commits_7d: int = 0
    commits_30d: int = 0
    open_boxes_30d_ago: Optional[int] = None
    verified_30d_ago: Optional[int] = None
    capability_ledger_age_days: Optional[int] = None


def gather_trend(git: Callable[[List[str]], str], *, today: str) -> Trend:
    """Point-in-time comparisons. Every field is optional: an unreadable
    history degrades to "unknown" and prints as such, never as zero."""
    t = Trend()

    def count(since: str) -> int:
        out = git(["rev-list", "--count", f"--since={since}", "HEAD"])
        return int(out) if out.isdigit() else 0

    t.commits_7d = count("7 days ago")
    t.commits_30d = count("30 days ago")

    sha = git(["rev-list", "-1", "--before=30 days ago", "HEAD"])
    if sha:
        old_bl = git(["show", f"{sha}:BACKLOG.md"])
        if old_bl:
            t.open_boxes_30d_ago = backlog_state(old_bl).open_boxes
        old_cap = git(["show", f"{sha}:docs/CAPABILITIES.md"])
        if old_cap:
            t.verified_30d_ago = capability_marks(old_cap)["verified"]

    last = git(["log", "-1", "--format=%cd", "--date=format:%Y-%m-%d",
                "--", "docs/CAPABILITIES.md"])
    if re.match(r"^\d{4}-\d{2}-\d{2}$", last or ""):
        try:
            from datetime import date
            y1, m1, d1 = (int(x) for x in last.split("-"))
            y2, m2, d2 = (int(x) for x in today.split("-"))
            t.capability_ledger_age_days = (date(y2, m2, d2) - date(y1, m1, d1)).days
        except ValueError:
            pass
    return t


# ---------------------------------------------------------------------------
# Render
# ---------------------------------------------------------------------------

def _delta(now: int, then: Optional[int]) -> str:
    if then is None:
        return "(30d: unknown)"
    d = now - then
    return f"(30d: {d:+d})"


def render(caps: Dict[str, int], bl: BacklogState, tr: Trend, *,
           today: str) -> str:
    """The block. Short on purpose — a readout nobody reads is the dev log's
    own failure mode, and this one sits at the top of that same file."""
    total = sum(caps.values()) or 1
    share = 100 * caps["verified"] // total
    lines = [
        BLOCK_START,
        "",
        f"## Dev status — {today}",
        "",
        "*Recomputed by `maro dev-status`; not a plan, a measurement. "
        "Leads with capability because the backlog is a findings log and "
        "its job is to grow — read it as a rate, not a total.*",
        "",
        "**Capability ledger** (`docs/CAPABILITIES.md`, row-level marks "
        "under the claimed≠probed rule)",
        "",
        f"| verified | target | aspirational | verified share |",
        f"|---|---|---|---|",
        f"| **{caps['verified']}** {_delta(caps['verified'], tr.verified_30d_ago)} "
        f"| {caps['target']} | {caps['aspirational']} | {share}% |",
        "",
    ]

    age = tr.capability_ledger_age_days
    if age is None:
        lines.append("- ⚠ ledger freshness unknown — treat the row above as "
                     "undated.")
    elif age >= 14:
        lines.append(f"- ⚠ **the ledger itself is {age} days stale.** A flat "
                     "verified count from an unmaintained doc and a flat "
                     "count from stalled work render identically; this one "
                     "may be bookkeeping lag, not a plateau.")
    else:
        lines.append(f"- ledger last updated {age}d ago — the count above is "
                     "current enough to read as real.")

    lines += [
        "",
        "**Throughput and fan-out**",
        "",
        f"- {tr.commits_7d} commits in 7d, {tr.commits_30d} in 30d",
        f"- **Actionable Stack** open boxes: **{bl.open_boxes}** "
        f"{_delta(bl.open_boxes, tr.open_boxes_30d_ago)}",
    ]
    if tr.open_boxes_30d_ago is not None and tr.commits_30d:
        net = bl.open_boxes - tr.open_boxes_30d_ago
        rate = net / (tr.commits_30d / 10.0)
        verdict = ("findings are outrunning closure"
                   if rate > 0 else "closure is outrunning findings")
        lines.append(f"- net new open items per 10 commits: **{rate:+.2f}** "
                     f"— {verdict}")
        lines.append("- ⚠ this delta counts one SECTION, so an archive pass "
                     "or a re-org moves it without any work changing hands. "
                     "Read the rate as a coarse direction, never as a score.")

    lines += [
        "",
        "**Actionable Stack, by kind** — the three things it contains, which "
        "look identical on the page",
        "",
        f"- {bl.entries_live} entries with open work "
        f"({bl.entries_gated} of them waiting on evidence, not on a person)",
        f"- {bl.entries_record} entries that are narrative records with no "
        f"open checkbox — shipped work, not queue",
    ]
    if bl.entries_no_stop_rule:
        lines += [
            "",
            f"**{len(bl.entries_no_stop_rule)} live entries declare no "
            "stopping rule** — no kill criterion, falsifier, or evidence "
            "gate. These are where 0→1-approaching-1 rabbit holes live:",
            "",
        ]
        for t in bl.entries_no_stop_rule[:8]:
            lines.append(f"  - {t}")
        if len(bl.entries_no_stop_rule) > 8:
            lines.append(f"  - … and {len(bl.entries_no_stop_rule) - 8} more")

    lines += ["", BLOCK_END]
    return "\n".join(lines)


def one_line(caps: Dict[str, int], bl: BacklogState, tr: Trend) -> str:
    total = sum(caps.values()) or 1
    return (f"dev-status: {caps['verified']}/{total} capabilities verified "
            f"({100 * caps['verified'] // total}%), {bl.open_boxes} open "
            f"items, {tr.commits_7d} commits/7d")


# ---------------------------------------------------------------------------
# Dev-log block placement
# ---------------------------------------------------------------------------

def splice_block(doc: str, block: str) -> str:
    """Put the block at the top of the dev log, under its intro.

    Replaces an existing block in place. Otherwise inserts before the
    first `## ` entry so the file's own header and reading instructions
    survive — the log is a narrative record and this is a header on it,
    not a new first entry.
    """
    if BLOCK_START in doc and BLOCK_END in doc:
        pre = doc.split(BLOCK_START)[0]
        post = doc.split(BLOCK_END, 1)[1]
        return pre + block + post

    lines = doc.splitlines(keepends=True)
    for i, line in enumerate(lines):
        if line.startswith("## "):
            return "".join(lines[:i]) + block + "\n\n" + "".join(lines[i:])
    return doc.rstrip("\n") + "\n\n" + block + "\n"


def compute(repo: Path, *, today: str, git: Optional[Callable] = None):
    """(caps, backlog_state, trend) for `repo`."""
    g = git or _git(repo)
    caps = capability_marks((repo / "docs" / "CAPABILITIES.md").read_text())
    bl = backlog_state((repo / "BACKLOG.md").read_text())
    tr = gather_trend(g, today=today)
    return caps, bl, tr
